server.port=8082
spring.application.name=store-service

#postgres
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/bookstore_db
spring.datasource.username=postgres
spring.datasource.password=postgres

#flyway
spring.flyway.enabled=true
spring.flyway.schemas=svc_store
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

#jpa
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=svc_store
spring.datasource.hikari.connection-init-sql=SET search_path TO svc_store

#keycloak
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://bookstore-keycloak:8080/realms/bookstore-realm/protocol/openid-connect/certs
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/bookstore-realm
keycloak.url=http://bookstore-keycloak:8080
keycloak.realm=bookstore-realm
keycloak.admin-client-id=bookstore-backend
keycloak.admin-client-secret=IGxyl7WDzZRfEnpNJnVGI1RHwF2G8xDG

#Kafka
spring.kafka.bootstrap-servers=${KAFKA_HOST:localhost}:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.group-id=store-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.type.mapping=com.bookstore.userservice.event.StoreApplicationApprovedEvent:com.bookstore.storeservice.event.StoreApplicationApprovedEvent
spring.kafka.consumer.properties.spring.json.trusted.packages=com.bookstore.*

#eureka
eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka/

