server.port=8088
spring.application.name=notification-service

# Mail
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_SMTP_STARTTLS_ENABLE:true}

# Kafka
spring.kafka.bootstrap-servers=${KAFKA_HOST:localhost}:9092
spring.kafka.consumer.group-id=notification-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.type.mapping=com.bookstore.userservice.event.StoreApplicationEmailEvent:com.bookstore.notificationservice.event.StoreApplicationEmailEvent, \
  com.bookstore.storeservice.event.CompleteProfileEmailEvent:com.bookstore.notificationservice.event.CompleteProfileEmailEvent, \
  com.bookstore.paymentservice.event.StripeOnboardingEmailEvent:com.bookstore.notificationservice.event.StripeOnboardingEmailEvent, \
  com.bookstore.userservice.event.EmployeeInvitationEmailEvent:com.bookstore.notificationservice.event.EmployeeInvitationEmailEvent
spring.kafka.consumer.properties.spring.json.trusted.packages=com.bookstore.*

# App
app.frontend.url=${APP_FRONTEND_URL:https://the-inkwell-ebon.vercel.app}

# Eureka Client
eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka
eureka.instance.preferIpAddress=true
