server.port=8081
spring.application.name=user-service

#postgres
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/bookstore_db
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

#flyway
spring.flyway.enabled=true
spring.flyway.schemas=svc_user
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

#jpa
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=svc_user
spring.datasource.hikari.connection-init-sql=SET search_path TO svc_user

#Kafka
spring.kafka.bootstrap-servers=${KAFKA_HOST:localhost}:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.group-id=user-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.type.mapping=com.bookstore.storeservice.event.CreateStoreOwnerEvent:com.bookstore.userservice.event.CreateStoreOwnerEvent
spring.kafka.consumer.properties.spring.json.trusted.packages=com.bookstore.*

#keycloak
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_JWK_SET_URI:http://keycloak:8080/realms/bookstore-realm/protocol/openid-connect/certs}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/bookstore-realm}
keycloak.url=${KEYCLOAK_URL:http://keycloak:8080}
keycloak.realm=${KEYCLOAK_REALM:bookstore-realm}
keycloak.admin-client-id=${KEYCLOAK_ADMIN_CLIENT_ID:bookstore-backend}
keycloak.admin-client-secret=${KEYCLOAK_ADMIN_CLIENT_SECRET:}

# Mail
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_SMTP_STARTTLS_ENABLE:true}

# App
app.frontend.url=${APP_FRONTEND_URL:http://localhost:5173}

#eureka
eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka/
