version: '3.8'

services:

  bookstore-postgres:
    image: postgres:16
    container_name: bookstore-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:Z
    networks:
      - bookstore-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5


  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: bookstore-keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://bookstore-postgres:5432/keycloak_db
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - bookstore-network
    depends_on:
      bookstore-postgres:
        condition: service_healthy


  discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
    networks:
      - bookstore-network
    depends_on:
      bookstore-postgres:
        condition: service_healthy


  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bookstore-postgres:5432/user_service_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    networks:
      - bookstore-network
    depends_on:
      bookstore-postgres:
        condition: service_healthy
      discovery-service:
        condition: service_started


  book-service:
    build: ./book-service
    container_name: book-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bookstore-postgres:5432/book_service_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    networks:
      - bookstore-network
    depends_on:
      bookstore-postgres:
        condition: service_healthy
      discovery-service:
        condition: service_started


networks:
  bookstore-network:
    driver: bridge


volumes:
  postgres_data:
  keycloak_data: