server.port=8085
spring.application.name=order-service

#postgress
spring.datasource.url=jdbc:postgresql://localhost:5432/bookstore_db
spring.datasource.username=postgres
spring.datasource.password=postgres

#flyway
spring.flyway.enabled=true
spring.flyway.schemas=svc_order
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

#jpa
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=svc_order
spring.datasource.hikari.connection-init-sql=SET search_path TO svc_order
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#keycloak
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/bookstore-realm/protocol/openid-connect/certs
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/bookstore-realm

#kafka
spring.kafka.bootstrap-servers=${KAFKA_HOST:localhost}:9092

#producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

#consumer
spring.kafka.consumer.client-id=order-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

#PIN
order.delivery.pin.length=6
order.delivery.pin.expiry-minutes=1440


eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

spring.cloud.openfeign.client.config.default.connect-timeout=5000
spring.cloud.openfeign.client.config.default.read-timeout=5000

