server.port=8084
spring.application.name=book-service

#Postgres
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/bookstore_db
spring.datasource.username=postgres
spring.datasource.password=postgres

#jpa
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=svc_book
spring.datasource.hikari.connection-init-sql=SET search_path TO svc_book

#keycloak
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://bookstore-keycloak:8080/realms/bookstore-realm/protocol/openid-connect/certs
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/bookstore-realm
keycloak.url=http://bookstore-keycloak:8080
keycloak.realm=bookstore-realm
keycloak.admin-client-id=bookstore-backend
keycloak.admin-client-secret=IGxyl7WDzZRfEnpNJnVGI1RHwF2G8xDG

#minio
minio.url=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin
minio.bucket-name=book-images

#eureka
eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka/
eureka.instance.prefer-ip-address=true