server.port=8083
spring.application.name=book-service

#Postgres
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/book_service_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://bookstore-keycloak:8080/realms/bookstore-realm/protocol/openid-connect/certs
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/bookstore-realm
eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka/